---
#
# This playbook create secret "secret" with data foo:foe. If secret "secret" exists - add data foo:foe.
#
- hosts: localhost
  tasks:
    - hashivault_secret:
        url: "https://vault.domain.local"
        authtype: ldap
        username: "user"
        password: "p@ssword"
        mount_point: "kv"
        state: present
        permanent: true
        secret: secret
        data:
            foo: foe
