---
- hosts: localhost
  tasks:
  - name: manage data disk 01
    decort_disk:
       authenticator: oauth2
       app_id: #Application id from SSO DigitalEnergy
       app_secret: #Application secret from SSO DigitalEnergy
       controller_url: "https://cloud.digitalenergy.online"
       account_name: "account_name"
       id: 111
       limitIO:
         read_bytes_sec: 100
         read_bytes_sec_max: 100
         read_iops_sec:  100
         read_iops_sec_max: 100
         size_iops_sec: 100
         write_bytes_sec: 100
         write_bytes_sec_max: 100
         write_iops_sec: 100
         write_iops_sec_max: 100
         total_bytes_sec: 0
         total_iops_sec: 0
         total_bytes_sec_max: 0
         total_iops_sec_max: 0
       verify_ssl: false

    delegate_to: localhost
