---
- hosts: localhost
  tasks:
    - hashivault_read:
        url: "https://vault.domain.local"
        authtype: ldap
        username: "uset"
        password: "p@ssword"
        mount_point: kv
        secret: secret
        key: foo
        version: 2
      register: key
