- hosts: localhost
  tasks:
   - name: Get auth token from vault
     set_fact:
       login_data: "{{ lookup('community.hashi_vault.vault_login', url='https://vault.domain.local', auth_method='ldap', username='username', password='pwd') }}"

   - name: Perform multiple kv2 reads with a single Vault login, showing the secrets
     vars:
       ansible_hashi_vault_auth_method: token
       ansible_hashi_vault_token: '{{ login_data | community.hashi_vault.vault_login_token }}'
       ansible_hashi_vault_engine_mount_point: kv
       paths:
         - secret
         - secret2
     ansible.builtin.debug:
       msg: "{{ lookup('community.hashi_vault.vault_kv2_get', *paths, auth_method='token', url='https://vault.domain.local') }}"
