---
#
# DECORT k8s module example
#
- hosts: ansible_master
  tasks:
  - name: obtain JWT
    decort_jwt:
      oauth2_url: "https://sso.digitalenergy.online"
      validity: 1200
      verify_ssl: false
    register: token
    delegate_to: localhost

  - name: create a VM named cluster-test
    decort_k8s:
      state: present
      started: True
      getConfig: True
      authenticator: jwt
      jwt: "{{ token.jwt }}"
      controller_url: "https://ds1.digitalenergy.online"
      name: "cluster-test"
      rg_id:  125
      k8ci_id: 18
      workers:
        - name: wg1
          ram: 1024
          cpu: 10
          disk: 10
          num: 1
        - name: wg2
          ram: 1024
          cpu: 10
          disk: 10
          num: 2
      verify_ssl: false
    delegate_to: localhost
    register: kube