---
#
# DECORT vins module example
#

- hosts: localhost
  tasks:
  - name: obtain JWT
    decort_jwt:
      oauth2_url: "https://sso.digitalenergy.online"
      validity: 1200
    register: my_jwt
    delegate_to: localhost

  - name: print out JWT
    debug:
      var: my_jwt.jwt
    delegate_to: localhost

  - name: Manage ViNS at resource group level
    decort_vins:
      authenticator: jwt
      jwt: "{{ my_jwt.jwt }}"
      controller_url: "https://ds1.digitalenergy.online"
      vins_name: "vins_created_by_decort_VINS_module"
      state: present
      rg_id: 198
      ext_net_id: -1
      ipcidr: "10.20.30.0/24"
      mgmtaddr: "10.20.30.1"
      custom_config: false
      config_save: false 
      verify_ssl: false

    register: managed_vins

  - name: print VINS facter
    debug:
      msg: "{{managed_vins.facts.password}}"
    when: managed_vins.facts.password is defined
