- hosts: localhost
  tasks:
  - name: create
    decort_rg:
       authenticator: oauth2
       controller_url: "https://cloud.digitalenergy.online"
       rg_name: "rg_created_by_module"
       # or
       #rg_id: 999
       account_id: 99
       quotas:
         cpu: 8
         ram: 4096
         disk: 20
         ext_ips: 10
         net_transfer: 200
       state: present
       verify_ssl: false
    register: my_rg
    delegate_to: localhost
