- hosts: localhost
  tasks:
  - name: create
    decort_rg:
       authenticator: oauth2
       controller_url: "https://cloud.digitalenergy.online"
       rg_name: "rg_created_by_module"
       account_id: 99
       owner: "user_1"  #Leave blank to set current user as owner. 
       quotas:
         cpu: 8
         ram: 4096
         disk: 20
         ext_ips: 10
         net_transfer: 200
       access:
         action: "grant"
         user: "user_2"
         right: "RCX"
       def_netType: "PRIVATE"
       ipcidr: ""                      "192.168.1.1"
       extNetId: 0
       extNetIp: ""                    "10.100.1.10"
       resType: 
       - vins 
       - compute
       state: present
       verify_ssl: false
    register: my_rg
    delegate_to: localhost
