- hosts: localhost
  tasks:
  - name: create
    decort_rg:
       authenticator: oauth2
       controller_url: "https://cloud.digitalenergy.online"
       rg_name: "test_rg"
       # or
       #rg_id: 999
       account_id: 99
       state: present
       permanently: True
       verify_ssl: false
    register: my_rg
    delegate_to: localhost
